language: python
matrix:
  include:
    - name: "Python 3.7.3 on Ubuntu 16.0.4"
      os: linux
      python: 3.7.3
      dist: xenial
      sudo: true
      env:
        DEPLOYMENT_ENV="true"

    - name: "Python 3.6 on Ubuntu 16.0.4"
      os: linux
      python: 3.6
      dist: xenial
      sudo: true

    - name: "Python 3.7.2 on OSX"
      os: osx
      language: shell
      dist: xcode10.2

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python  --version=3.7.2
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

cache: pip
# install dependencies
install:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then pip3 install --upgrade pip; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_wait pip install --no-cache-dir -e .; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then travis_wait pip3 install --no-cache-dir -e .; fi
  - if [ "$DEPLOYMENT_ENV" = "true" ]; then travis_wait pip3 install mkdocs mkdocs-material pymdown-extensions pygments; fi

before_script: cd tests/ci_tests
# run tests
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_wait python full_test.py; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then travis_wait python3 full_test.py; fi
  - cd ../..

before_deploy:
  - cd docs
  - mkdocs build --verbose --clean --strict
  - cp -r site ../
  - cd ..

# deploy to pip
deploy:
  - provider: pypi
    user: "mindsdb_sysadmin"
    password: $PYPI_SYSADMIN_PASSWORD
    on:
      branch: master
      condition: $DEPLOYMENT_ENV = "true"

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
      branch: master
      condition: $DEPLOYMENT_ENV = "true"
